# 공통

spring:
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rowingMachineMVP.**.vo
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 80


logging:
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
  file:
    name: logs
    max-history: 7
    max-size: 5KB
    total-size-cap: 1MB
  level:
    root: INFO
    com:
      rowingMachineMVP: DEBUG

---

# local

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/rowing_db?autoReconnect=true
    username: root
    password: 1234


---

# was

spring:
  config:
    activate:
      on-profile: was
  datasource:
    url: jdbc:mysql://rowingmachine.cakioqitx4ac.ap-northeast-2.rds.amazonaws.com:3306/rowing_db?autoReconnect=true
    username: root
    password: root1234